name: Run Unit Tests
on:
  workflow_call:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: google_apis
            #emulator-options: -no-boot-anim
          script: |
            pip install '.[async,dev]'
            pip install -r requirements.txt
            pip install pytest
            python3 -m pytest test -s -v --junitxml=junit/test-results.xml
            python3 -m pytest test_async -s -v --junitxml=junit/test-async-results.xml

